- name: Install Prerequisites
  ansible.builtin.include_tasks: prerequisites.yml 

- name: Initialisation
  ansible.builtin.include_tasks: initialisation.yml
  when: "'master-1' in ansible_hostname"

- name: Join server masters and workers
  include_tasks: join.yml
  when: "'master-1' not in ansible_hostname"
