---
# handlers file for roles/kubernetes
- name: restart_containerd
  ansible.builtin.service:
    name: containerd
    state: restarted

- name: update_apt_cache
  ansible.builtin.apt:
    update_cache: true
